import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
         <Toaster
        position="top-right"
        toastOptions={{
          style: {
            background:
              "linear-gradient(135deg, rgba(59,130,246,0.9), rgba(168,85,247,0.9))", // from-primary-400 to-secondary-400
            color: "#fff",
            border: "1px solid rgba(255, 255, 255, 0.2)",
            borderRadius: "1rem",
            backdropFilter: "blur(12px)",
            boxShadow: "0 4px 20px rgba(0, 0, 0, 0.3)",
            padding: "12px 16px",
            fontWeight: 500,
          },
          success: {
            duration: 3000,
            iconTheme: {
              primary: "#38bdf8", // primary-300
              secondary: "#fff",
            },
          },
          error: {
            style: {
              background:
                "linear-gradient(135deg, rgba(239,68,68,0.9), rgba(220,38,38,0.9))", // red gradient
              border: "1px solid rgba(255, 255, 255, 0.2)",
            },
            iconTheme: { primary: "#ef4444", secondary: "#fff" },
          },
          loading: {
            duration: Infinity,
            iconTheme: { primary: "#facc15", secondary: "#fff" }, // yellow
          },
        }}
      />
      </body>
    </html>
  );
}
